### ISSUE TITLE
403 returned by the server

### ISSUE THREAD

**Issue by pabloariasal** [tomslee/airbnb#1]
It appears to be a new security setup on the server side blocking known bot agents. Thus status code 403 is returned when requests are issued. Proposed solution [here](http://stackoverflow.com/questions/16627227/http-error-403-in-python-3-web-scraping) is to add user agent header to the request to mock standard software.

**Comment by tomslee** [comment]
Hi Pablo,

Thanks for identifying the problem and pointing to the solution. I've
updated the source on github with your fix, in case you want to stay
current.

I'll have to cut back on the work I've been doing with this project, as I
have a book to write on the subject :). I'll answer what questions I can
and would be very interested in the work you are doing.

All the best,

Tom

**Comment by pabloariasal** [comment]
Hello Tom,

Thanks a lot for taking the time to fix the problem. We also had some
trouble creating the tables using the provided sql script on Windows, but
that is apparently a known issue.
I'm not using the script directly, but a friend of mine is. She couldn't
get it running so asked for my help, the computer nerd. She said it was for
a school project she is working on, but I don't know any details. Next time
I see her I will ask her for a more thorough description of what she is
doing.

Best regards,

Pablo.
